### PR TITLE
Fix panic in StateFromPeopleNowPresent modifier

### LINKED ISSUE #102: StateFromPeopleNowPresent breaks when no data is available
```
[2019-12-31T16:13:57Z INFO  spaceapi_server::server::handlers] GET / from 172.17.0.1:58012
[2019-12-31T16:13:57Z WARN  spaceapi_server::server::handlers] Could not retrieve key 'temperature_raspi' from Redis, omiting the sensor
[2019-12-31T16:13:57Z WARN  spaceapi_server::server::handlers] Could not retrieve key 'people_now_present' from Redis, omiting the sensor
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/slice/mod.rs:2539:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: <spaceapi_server::modifiers::StateFromPeopleNowPresent as spaceapi_server::modifiers::StatusModifier>::modify
  10: <spaceapi_server::server::handlers::ReadHandler as iron::middleware::Handler>::handle
  11: <alloc::boxed::Box<(dyn iron::middleware::Handler + 'static)> as iron::middleware::Handler>::handle
  12: router::router::Router::handle_method
  13: <router::router::Router as iron::middleware::Handler>::handle
  14: <iron::iron::RawHandler<H> as hyper::server::Handler>::handle
  15: <hyper::server::Worker<H>>::handle_connection
  16: hyper::server::listener::spawn_with::{{closure}}
```

This happened after restarting the server with an empty database. Apparently it cannot deal with missing data.

### PR DESCRIPTION
**Pull request by dbrgn**
Fixes #102.

## Checklist

- [x] Tests added if applicable
- [x] README updated if applicable
- [x] CHANGELOG updated if applicable
- [x] If a commit includes a breaking change, include the string `[breaking-change]` somewhere in the commit message

### CODE REVIEW

File: src/modifiers.rs [hunk 1]
```diff
@@ -19,7 +19,8 @@ impl StatusModifier for StateFromPeopleNowPresent {
         let people_now_present: Option<u64> = status
             .sensors
             .as_ref()
-            .map(|sensors| sensors.people_now_present[0].value);
+            .and_then(|sensors: &api::Sensors| sensors.people_now_present.first())
+            .map(|sensor: &api::PeopleNowPresentSensor| sensor.value);
```
Comment (rnestler) [inline src/modifiers.rs]: Should we log if no sensor is present? It probably deserves a warning, since if one adds the modifier one would expect the sensor to be present.

Comment (dbrgn) [reply src/modifiers.rs]: This can also happen if a sensor is configured, but when the database is still empty. This is already being logged, so I don't think we need to do anything else.

Comment (rnestler) [reply src/modifiers.rs]: OK.

**Comment by dbrgn** [comment]
> OK

@rnestler well, then, can you approve this PR please?
